name: vue
version: 0.4.1+1
description: Vue bindings for Dart
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  analyzer: '>=0.33.0 <0.35.0'
  async: ^2.0.7
  build: ^1.0.1
  csslib: ^0.14.4
  html: ^0.13.3
  js: ^0.6.1
  sass: ^1.8.0
  sass_builder: ^2.1.0
  scopify: ^0.2.1
  source_maps: ^0.10.6
  source_span: ^1.4.0
  uuid: ^1.0.0
